trigger: 
 branches:
    include:
      - master
      - Development

pool:

  vmImage: "vs2017-win2016"

steps:
- task: UiPathInstallPlatform-preview@2

- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'Orchestrator'
    testProjectPath: 'Order Process/project.json'
    environment: 'ThomasStockerEnvironment'
    folderName: 'ThomasStocker'
    testReportDestination: 'result.xml'

- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 
    outputType: 'Process'
    orchestratorConnection: 'Orchestrator'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'


- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'Orchestrator'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'ThomasStocker'

