trigger:
- master
- releases/*

pool:

  vmImage: "vs2017-win2016"

steps:
- task: UiPathInstallPlatform-preview@2

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      dir
      echo Hello world

- task: UiPathAssets@2
  inputs:
    orchestratorConnection: 'staging_default'
    folderName: 'Thomas Stocker'
    assetActionType: 'Deploy'
    csvFile: 'assets.csv'
    traceLevel: 'Verbose'