trigger:
- master

pool:

  vmImage: "vs2017-win2016"

steps:
- task: UiPathInstallPlatform-preview@2



- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'Order Process/project.json'
    outputType: 'Process'
    orchestratorConnection: 'Orchestrator'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    

- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'Orchestrator'
    packagesPath: 'Output'
    folderName: 'ThomasStocker'

